message-bus:
  type: activemq
  broker-url: tcp://${MBUS_URL:localhost}:61616
  topic: demo.book
spring:
  artemis:
    broker-url: tcp://${MBUS_URL:localhost}:9876
    mode: native
    embedded:
      topics: demo.book
