spring:
  jpa:
    database: oracle
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:format_sql: true
      dialect: org.hibernate.dialect.Oracle12gDialect
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/XEPDB1}
    username: ${DB_USERNAME:novel}
    password: ${DB_PASSWORD:novel1}
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    user: ${DB_USERNAME:novel}
    password: ${DB_PASSWORD:novel1}
    locations: "classpath:db/migration/{vendor}"
    enabled: true
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/XEPDB1}
