spring:
  application:
    name: novel-ideas-v1
  mvc:
    problemdetails:
      enabled: true
  ssl:
    bundle:
      pem:
        web-server:
          truststore:
            certificate: ${TRUSTSTORE:/home/${user}/certs/myCA.pem}
          keystore:
            certificate: ${KEYSTORE-PUB:/home/${user}/certs/devcert.pem}
            private-key: ${KEYSTORE-KEY:/home/${user}/certs/devcert.key}
            private-key-password: ${KEYSTORE-PASSWORD}
          options:
            ciphers:
              - TLS_AES_256_GCM_SHA384
              - TLS_CHACHA20_POLY1305_SHA256
            enabled-protocols: TLSv1.3

info:
  app:
    # Get the version from the POM file and injected into SpringDoc Info
    version: @project.version@

management:
  endpoints:
    probes:
      enabled: true
    web:
      exposure:
        include:
          - health
          - info
#  endpoint:
#    health:
#      group:
#        readiness:
#          include: "readinessState"

message-bus:
  type: none

server:
  servlet:
    context-path: "/"
  port: ${PORT:10443}
  http2:
    enabled: true
  ssl:
    bundle: "web-server"

springdoc:
  swagger-ui:
    #For sorting endpoints alphabetically
    operations-sorter: alpha
    #For sorting tags alphabetically
    tags-sorter: alpha
  #For sorting schemas
  writer-with-order-by-keys: true

