server:
  port: ${PORT:10443}
  http2:
    enabled: true
  ssl:
    enabled: true
    trust-store: ${TRUSTSTORE:/home/${user}/certs/truststore.p12}
    trust-store-password: ${TRUSTSTORE-PASSWORD}
    trust-store-type: PKCS12
    key-store: ${KEYSTORE:/home/${user}/certs/keystore.p12}
    key-store-password: ${KEYSTORE-PASSWORD}
    key-store-type: PKCS12
    ciphers:
    - TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
    - ECDHE-RSA-AES256-SHA384
    - ECDHE-RSA-AES256-GCM-SHA256
    - ECDHE-RSA-AES256-GCM-SHA384
    enabled-protocols:
    - TLSv1.2
    - TLSv1.3
