server:
  servlet:
    context-path: "/"
  port: ${PORT:10443}
  http2:
    enabled: true
  ssl:
    enabled: true
    trust-store: ${TRUSTSTORE:/home/${user}/certs/truststore.p12}
    trust-store-password: ${TRUSTSTORE-PASSWORD}
    trust-store-type: PKCS12
    key-store: ${KEYSTORE:/home/${user}/certs/keystore.p12}
    key-store-password: ${KEYSTORE-PASSWORD}
    key-store-type: PKCS12
    ciphers:
    - TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
    - ECDHE-RSA-AES256-SHA384
    - ECDHE-RSA-AES256-GCM-SHA256
    - ECDHE-RSA-AES256-GCM-SHA384
    enabled-protocols:
    - TLSv1.2
    - TLSv1.3
info:
  app:
    # Get the version from the POM file and injected into SpringDoc Info
    version: @project.version@
springdoc:
  swagger-ui:
    #For sorting endpoints alphabetically
    operationsSorter: alpha
    #For sorting tags alphabetically
    tagsSorter: alpha
