CREATE TABLE book
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR2(255) NOT NULL,
    description VARCHAR2(4000),
    start_date  TIMESTAMP                                NOT NULL,
    state_id    INTEGER,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE book_character_profile
(
    book_id              INTEGER NOT NULL,
    character_profile_id INTEGER NOT NULL,
    CONSTRAINT pk_book_character_profile PRIMARY KEY (book_id, character_profile_id)
);

CREATE TABLE book_state
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state      VARCHAR2(255) NOT NULL,
    is_deleted NUMBER(1) NOT NULL,
    CONSTRAINT pk_book_state PRIMARY KEY (id)
);

CREATE TABLE character_gender
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gender     VARCHAR2(255) NOT NULL,
    is_deleted NUMBER(1) NOT NULL,
    CONSTRAINT pk_character_gender PRIMARY KEY (id)
);

CREATE TABLE character_importance
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    importance VARCHAR2(255) NOT NULL,
    is_deleted NUMBER(1) NOT NULL,
    CONSTRAINT pk_character_importance PRIMARY KEY (id)
);

CREATE TABLE character_profile
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_name          VARCHAR2(255),
    title                   VARCHAR2(255),
    first_name              VARCHAR2(255),
    middle_name             VARCHAR2(255),
    surname                 VARCHAR2(255),
    nick_name               VARCHAR2(255),
    character_gender_id     INTEGER,
    character_importance_id INTEGER                                  NOT NULL,
    physical_description    VARCHAR2(4000),
    inner_goal              VARCHAR2(4000),
    outer_goal              VARCHAR2(4000),
    function_in_story       VARCHAR2(4000),
    date_of_birth           date,
    CONSTRAINT pk_characterprofile PRIMARY KEY (id)
);

ALTER TABLE character_gender
    ADD CONSTRAINT uc_character_gender_gender UNIQUE (gender);

CREATE INDEX idx_book_state_is_deleted ON book_state (is_deleted);

CREATE INDEX idx_char_imp_is_deleted ON character_importance (is_deleted);

CREATE INDEX idx_character_gender_is_deleted ON character_gender (is_deleted);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_STATE FOREIGN KEY (state_id) REFERENCES book_state (id);

ALTER TABLE character_profile
    ADD CONSTRAINT FK_CHARACTERPROFILE_ON_CHARACTER_GENDER FOREIGN KEY (character_gender_id) REFERENCES character_gender (id);

ALTER TABLE character_profile
    ADD CONSTRAINT FK_CHARACTERPROFILE_ON_CHARACTER_IMPORTANCE FOREIGN KEY (character_importance_id) REFERENCES character_importance (id);

ALTER TABLE book_character_profile
    ADD CONSTRAINT fk_boochapro_on_book FOREIGN KEY (book_id) REFERENCES book (id);

ALTER TABLE book_character_profile
    ADD CONSTRAINT fk_boochapro_on_character_profile FOREIGN KEY (character_profile_id) REFERENCES character_profile (id);